### ISSUE TITLE
Confusing Error Message For Do-Nothing Input Used With observeFlows()

### ISSUE THREAD

**Issue by commonsguy** [copper-leaf/ballast#72]
As with Ballast examples, I have an `InputHandler` with a `when` as the entirety of `handleInput()`, branching based on the input type. At the end of the `when` branch for one input, I had an `observeFlows()` call. When I ran the code, I got a stack trace:

```
2024-10-01 15:25:13.047 E  com.copperleaf.ballast.core.BallastLoggingException: java.lang.IllegalStateException: Input was not handled properly. To ensure you're following the MVI model properly, make sure any side-jobs are executed in a `sideJob { }` block.
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.core.LoggingInterceptor$start$1$1.invokeSuspend(LoggingInterceptor.kt:55)
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.core.LoggingInterceptor$start$1$1.invoke(Unknown Source:8)
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.core.LoggingInterceptor$start$1$1.invoke(Unknown Source:4)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:219)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:11)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:113)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:82)
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.internal.actors.InterceptorActor$startInterceptorsInternal$1$notificationFlow$1.invokeSuspend(InterceptorActor.kt:46)
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.internal.actors.InterceptorActor$startInterceptorsInternal$1$notificationFlow$1.invoke(Unknown Source:11)
2024-10-01 15:25:13.047 E  	at com.copperleaf.ballast.internal.actors.InterceptorActor$startInterceptorsInternal$1$notificationFlow$1.invoke(Unknown Source:6)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.FlowKt__LimitKt$transformWhile$1$invokeSuspend$$inlined$collectWhile$1.emit(Limit.kt:139)
2024-10-01 15:25:13.047 E  	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
2024-10-01 15:25:13.048 E  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
2024-10-01 15:25:13.048 E  Caused by: java.lang.IllegalStateException: Input was not handled properly. To ensure you're following the MVI model properly, make sure any side-jobs are executed in a `sideJob { }` block.
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.core.DefaultGuardian.checkUsedProperly(DefaultGuardian.kt:80)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.core.DefaultGuardian.close(DefaultGuardian.kt:62)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.scopes.InputHandlerScopeImpl.close$ballast_api_debug(InputHandlerScopeImpl.kt:64)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.actors.InputActor$safelyHandleInput$2.invokeSuspend(InputActor.kt:152)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.actors.InputActor$safelyHandleInput$2.invoke(Unknown Source:8)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.actors.InputActor$safelyHandleInput$2.invoke(Unknown Source:4)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
2024-10-01 15:25:13.048 E  	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.actors.InputActor.safelyHandleInput(InputActor.kt:140)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.actors.InputActor.safelyHandleQueued$ballast_api_debug(InputActor.kt:118)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.internal.scopes.InputStrategyScopeImpl.acceptQueued(InputStrategyScopeImpl.kt:47)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.core.FifoInputStrategy$processInputs$2.emit(FifoInputStrategy.kt:38)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.core.FifoInputStrategy$processInputs$2.emit(FifoInputStrategy.kt:35)
2024-10-01 15:25:13.048 E  	at com.copperleaf.ballast.core.ChannelInputStrategy$start$1$invokeSuspend$$inlined$filter$1$2.emit(Emitters.kt:219)
2024-10-01 15:25:13.049 E  	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
2024-10-01 15:25:13.049 E  	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
2024-10-01 15:25:13.049 E  	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
2024-10-01 15:25:13.049 E  	... 6 more
```

Given the mention of `sideJob()`, the error message suggests that the problem is with the `observeFlow()` call itself, since that's a wrapper around `sideJob()`. It turned out that the problem was in the `when` branch for the input emitted by my flow that I am observing. If I have this, I get the above stack trace:

```kotlin
is Input.TheOneCausingProblems -> {
    Timber.d("hello world")
}
```

If I add a do-nothing state update, the stack trace goes away:

```kotlin
is Input.TheOneCausingProblems -> {
    Timber.d("hello world")
    updateState { state -> state }
}
```

If this stack trace is legit, I would not have guessed "failed to update a state from an input" as being tied to this message. The message is already long, but it would be cool if there were some way to tie this scenario into it (e.g., have the message include a documentation URL that explains potential causes/fixes).

**Comment by cjbrooks12** [comment]
This is intentional behavior, but you're right that it does need better documentation around it. I've been on paternity leave for a while but will be returning to work soon, so will try to get this improved for the next version.

There are checks in place to help ensure each Input is processed correctly, which, among other things, checks that _something_ was done during the handling of an Input. Since MVI is a "pure Functional-programming" system at its core, each Input should either change the State, produce an Event, or run a Side Effect safely within a `sideJob`. Having this check is intended to help make sure you're not using an Input that produces Side Effects which are not carefully managed, or otherwise doing something that you _think_ works but in reality does not. As an analog to Compose, consider that it is incorrect to write a "side effect" directly within the Composable code, and it should always be wrapped in a `SideEffect { }` block.

However, it's pretty normal to have some Inputs not have their behavior defined _yet_, or to have some conditional logic cause an Input to have no effect for _part_ of it's InputHandler logic. For these cases, you should call [noOp()](https://github.com/copper-leaf/ballast/blob/main/ballast-api/src/commonMain/kotlin/com/copperleaf/ballast/InputHandlerScope.kt#L84-L88) rather than `updateState { state -> state }` to make it more explicit that you're aware the behavior was intentionally skipped.

**Comment by commonsguy** [comment]
OK, thanks!
